#!/bin/bash

#Pietro_Malzone_04/12/2023

touch File1

echo -e ">1A34:A|PDBID|CHAIN|SEQUENCE
MGRGKVKPNRKSTGDNSNVVTMIRAGSYPANTONIOKVNPTPT
WVRAIPFEVSVQSGIAFKVPVGSLFSANFRTDSFTS
VTVMSVRAWTQLTPPVNEYSFVRLKPLFKTGDSTEE
FEGRASNINTRASVGYFDSFDSAOLMIDNDASL" >> File1

touch File2

echo -e "RIPTNLRQNTVAADNVCEVR FDSFFDF
SNCRANTIDILUVIANOQVALVISCCFN
>1A34:B|PDBID|CHAIN|SEQUENCE
AAAAAAAAAA
>1A34:C|PDBID|CHAIN|SEQUENCE
UUUUUUUUUUo" >> File2


cat File1
cat File2
